### ISSUE TITLE
Fix for node 7

### ISSUE THREAD

**Issue by jefflembeck** [npm/etcetera#137]
This doesn't pass `install` correctly on node 7 on Travis.

@nexdrew has pointed out that it is likely due to https://github.com/abbr/deasync/issues/73

We should put in a PR for node-etcd to update with a new deasync (and then get tests passing)

**Comment by jefflembeck** [comment]
PR in https://github.com/stianeikeland/node-etcd/pull/67

**Comment by mmalecki** [comment]
We don't use sync etcd queries. I'll move us over to `etcdjs` (npm/etcetera#153).

**Comment by mmalecki** [comment]
This has been long fixed \o/
